### ISSUE TITLE
issues when loading a png (corruption?)

### ISSUE THREAD

**Issue by tlacaelelrl** [chafey/cornerstoneWebImageLoader#14]
The png can be seen here https://v2.vetology.net/patient-manager/image?id=1100414&id2=5367541

Then if you go to the sample page http://rawgit.com/chafey/cornerstoneWebImageLoader/master/examples/index.html
and load the same issue, when it is added to the canvas, the image can't be recognized any longer

Is there some setting I can change so mages display correctly? See screenshot below:
![sample](https://user-images.githubusercontent.com/1902898/30352801-b661d8ba-97e7-11e7-8c13-6a5e028bd74c.png)

**Comment by swederik** [comment]
The image at that URL is unreachable to me. Can you post it here or change the link?

**Comment by tlacaelelrl** [comment]
I decided to go with jpegs for the mean time so the pngs were deleted, will post back if we start getting this issues after we start generating the new pngs;
