### ISSUE TITLE
Readme includes instructions for building/running w/ Grunt, but project appears to use webpack

### ISSUE THREAD

**Issue by dannyrb** [chafey/cornerstoneWebImageLoader#16]
I believe the documentation is outdated. There does not appear to be a `bower.json` and `grunt` does not appear to be included as a local dependency. However, `webpack` appears as a dependency, and there are a number of NPM scripts.

**Comment by swederik** [comment]
Whoops, guess I forgot to update that... Thanks for letting me know!
