### ISSUE TITLE
Package import issue

### ISSUE THREAD

**Issue by dannyrb** [chafey/cornerstoneWebImageLoader#17]
Missing `main` tag in `package.json` requires a more explicit path to use. You can see expected usage versus actual usage below. Here is an example of the tag in `cornerstoneWADOImageLoader`:

https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/package.json#L15

**Expected:**

_Global_
`<script src="https://unpkg.com/cornerstone-web-image-loader"></script>`

_Import_
`import * as cornerstoneWebImageLoader from 'cornerstone-web-image-loader`

**Actual:**

_Global_
`<script src="https://unpkg.com/cornerstone-web-image-loader@0.8.2/dist/cornerstoneWebImageLoader.js"></script>`

_Import_
`import * as cornerstoneWebImageLoader from 'cornerstone-web-image-loader/dist/cornerstoneWebImageLoader.js`

If I get a :+1:, I'll make a quick PR

**Comment by dannyrb** [comment]
I lied @swederik, I made a PR without your 👍 
Simple single liner.

**Comment by dannyrb** [comment]
@swederik is there a way to trigger an automatic NPM package release?

**Comment by swederik** [comment]
Not that I'm aware of :-( What's your npm username?

**Comment by swederik** [comment]
Not that I know of, but I haven't looked too hard. I just published 0.8.3

**Comment by dannyrb** [comment]
Thanks for publishing a release :+1:
You can find me on NPM here: [https://www.npmjs.com/~dannyrb](https://www.npmjs.com/~dannyrb)

If you find yourself spending a lot of time manually publishing releases, we can have a conversation around Continuous Integration / release / deployment?

Closing, because that publish fixed my issue 🎉 
You can see for yourself by visiting: https://unpkg.com/cornerstone-web-image-loader
