### ISSUE TITLE
TypeError: errorLoadingHandler is not a function

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstoneWebImageLoader#6]
When using cornerstoneTools with webImageLoader, the error "TypeError: errorLoadingHandler is not a function" is raised.

It looks like that handler is implemented in WADOImageLoader but not in WebImageLoader.

**Comment by swederik** [comment]
Hmm this is probably my fault. Where are you getting the TypeError?

**Comment by leonardorame** [comment]
You are right, the error comes from cornerstoneTools, stackPrefetch.js line 181.

**Comment by swederik** [comment]
That should fix it.
