### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by okbel** [chafey/cornerstoneWebImageLoader#9]
There's a wrong labeled version and it's updating to an old version of the loader.
'bower install cornerstoneWebImageLoader' gets the 0.7.2 version instead of the latest.

<img width="544" alt="screen shot 2015-11-23 at 5 47 40 pm" src="https://cloud.githubusercontent.com/assets/1401559/11349315/634d1cd2-920a-11e5-8c32-d54c73a4a582.png">

**Comment by chafey** [comment]
I just pushed a new version - can you verify that everything is working properly now?

**Comment by chafey** [comment]
@okbel is this issue resolved?  Will close in 7 days if I don't hear back

**Comment by okbel** [comment]
@chafey Yes! Thank you!

**Comment by chafey** [comment]
OK great, closing. Thanks
